version: '3.9'
services:
  app1: &app
    build: .
    hostname: app1
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgresql://localhost:5432/rinhadb
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: pass
      DB_POOL: 40
      # REQ_TIMEOUT: "2000"
    expose:
      - "8080"
    depends_on:
      - postgres
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:8080/ || exit 1
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 5s

  app2:
    <<: *app
    hostname: app2

  postgres:
    image: postgres:latest
    hostname: postgresql-db
    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app1: 
        condition: service_healthy
      app2:
        condition: service_healthy
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'